package models;
// Generated Aug 23, 2019 9:15:04 PM by Hibernate Tools 4.3.1



/**
 * Cours generated by hbm2java
 */
public class Cours  implements java.io.Serializable {


     private Integer id;
     private Specialitee specialitee;
     private String nom;
     private int coeff;

    public Cours() {
    }
    
    

    public Cours(Specialitee specialitee, String nom, int coeff) {
       this.specialitee = specialitee;
       this.nom = nom;
       this.coeff = coeff;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Specialitee getSpecialitee() {
        return this.specialitee;
    }
    
    public void setSpecialitee(Specialitee specialitee) {
        this.specialitee = specialitee;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public int getCoeff() {
        return this.coeff;
    }
    
    public void setCoeff(int coeff) {
        this.coeff = coeff;
    }




}


