package models;
// Generated Aug 23, 2019 9:15:04 PM by Hibernate Tools 4.3.1



/**
 * Formateurs generated by hbm2java
 */
public class Formateurs extends Personne implements java.io.Serializable {
 
    String grade; 
    int nbHeure; 
    double salaire; 

    public Formateurs( Integer id, String nom, String prenom, String email, String telephone, String genere,String grade,int nbHeure, double salire ) {
        super(id, nom, prenom, email, telephone, genere);
        this.grade = grade;
        this.nbHeure=nbHeure;
        this.salaire=salaire; 
    }

    public Formateurs() {
        super();
    }
    


    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }

    public int getNbHeure() {
        return nbHeure;
    }

    public void setNbHeure(int nbHeure) {
        this.nbHeure = nbHeure;
    }

    public double getSalaire() {
        return salaire;
    }

    public void setSalaire(double salaire) {
        this.salaire = salaire;
    }
    

    
    @Override
    public String toString() {
        return "Formateurs{" + "grade=" + grade + '}';
    }
    



    @Override
    public double calculeSalaire(String grade, int nbh) {

            if (grade=="1er"){
            salaire=400+(nbh*1.4); 
        }else {
            if (grade=="2er"){
                salaire=400+(nbh+1.6); 
            }
            else{
                salaire=400+(nbh+1.9); 
            }
        }

        return salaire ; 
    }

 

    
    
    
    

}